### ISSUE TITLE
Redirect to Main WPCasa Settings Page after successful "single" activation of WPCasa

### ISSUE THREAD

**Issue by JoeHana** [wpsight/wpcasa#108]
## Prerequisites

- [x] This issue is neither a bug report nor a feature request.
- [x] I've experience in webdevelopment
- [ ] I'm new to WordPress

## Description
In cases where WPCasa gets individually enabled, it should redirect to the WPCasa Dashboard (including the notice about successful activation) in order to have the user directly setting up all the settings.

**Comment by igorchernenko92** [comment]
done
