### ISSUE TITLE
[BUG] PHP Notice: Undefined index

### ISSUE THREAD

**Issue by sebastienserre** [wpsight/wpcasa#117]
Hello,

I'm debugging something else and my debug log is full of `
PHP Notice:  Undefined index: page in /wp-content/plugins/wpcasa/includes/admin/class-wpsight-admin-page-licenses.php on line 14
`

## Environment

**Server & Site**
- PHP Version: 7.3.18
 - WordPress Version 5.4.1
 - WPCasa Version 1.2.4

**Comment by igorchernenko92** [comment]
Hello
We gonna release fix for that in few days
Thanks

**Comment by miltonardila** [comment]
> Hello
> We gonna release fix for that in few days
> Thanks

Hi, do you know if this has a solution yet? I have the same problem today. Thank you.

**Comment by motioncompany** [comment]
Hello,
when will get a fix for this problem?
On your website you write "professional real estate websites" but it is not possible work like a professional with this issue.

Please reply to our request.
Thanks!
