### ISSUE TITLE
missing wpcasa in wordpress repository

### ISSUE THREAD

**Issue by Jimmi08** [wpsight/wpcasa#122]
Sorry, if I missed something, but why is not this plugin anymore between official WordPress plugins? You can't install it directly.
Thanks

**Comment by JoeHana** [comment]
Hey Jimmi,

WPCasa is currently under review but will be back soon again. Sorry for the circumstances.

**Comment by Jimmi08** [comment]
Hi, it is still not there. Is there any problem with plugin?

**Comment by codestylist** [comment]
@Jimmi08 I'm not sure if you've noticed yet: WPCasa is back at the WordPress directory. Feel free to download at https://wordpress.org/plugins/wpcasa/

**Comment by Jimmi08** [comment]
> @Jimmi08 I'm not sure if you've noticed yet: WPCasa is back at the WordPress directory. Feel free to download at https://wordpress.org/plugins/wpcasa/

Yes, thank you. I have got email about new maintainer of wpcasa.
