### ISSUE TITLE
Question - agents as custom post type

### ISSUE THREAD

**Issue by Jimmi08** [wpsight/wpcasa#125]
## Prerequisites

- [x] This issue is neither a bug report nor a feature request.
- [x] I've experience in webdevelopment
- [ ] I'm new to WordPress

## Description
I am just curious about the next development or plans.  Agents are now users with user meta fields.  From my experience, working with agents as custom post type is easier.  
 
## Additional context
I am not asking for change. Only if there are any plans or idea how to use them as CPT without breaking wpcasa functionality (in child theme or plugin)

Thanks

**Comment by codestylist** [comment]
Thank you @Jimmi08 for the question. Agents are users. They have the ability to log in and edit listings. That's why there is no plan to move agents into their own custom post type. We want to utilize deep WordPress features wherever we can use them.
I hope this makes it clear for you.
