### ISSUE TITLE
[BUG] PHP 8.2 warning related to Ninja Form Addon

### ISSUE THREAD

**Issue by Jimmi08** [wpsight/wpcasa#126]
## Prerequisites

- [x] I've read and tried everything from the [troubleshooting guide](https://docs.wpcasa.com/article/troubleshooting-guide/), but the issue persists.
- [x] I've experience in webdevelopment
- [ ] I'm new to WordPress
- [ ] I've already fixed/I'm going to fix this bug and have submitted/going to submit it as PR.

## Description
If you install Ninja Form addon, there are PHP warnings in PHP 8.2 
Deprecated: Creation of dynamic property WPSight_Framework::$ninja_forms is deprecated in  wp-content\plugins\wpcasa-ninja-forms\wpcasa-ninja-forms.php on line 85

This warning causes new warnings like Warning: Cannot modify header information - headers already sent by (output started at  \wp-content\plugins\wpcasa-ninja-forms\wpcasa-ninja-forms.php:85) in  \includes\misc.php on line 1438
 

## Fix
Everything was fixed just by adding new property to WPSight_Framework in wpcasa.php

`    public $ninja_forms;`

I could sent PR but I am not sure if this is correct fix. 

## Environment

**Server & Site**
- PHP Version: [8.2.0]
 - WordPress Version [6.6]
 - WPCasa Version [1.2.13]
 - WPCasa Ninja Version [2.0.0]

**Comment by codestylist** [comment]
Thank you @Jimmi08 for your message. We have not noticed this issue yet and will investigate it further.

**Comment by codestylist** [comment]
Hi @Jimmi08 .
We have fixed this issue with lates WPCasa 1.3.1 
Thank you for your support to makw WCasa better.
Best, Sandro
