### ISSUE TITLE
Report after testing Ninja Forms with PHP 8.2

### ISSUE THREAD

**Issue by Jimmi08** [wpsight/wpcasa#127]
## Prerequisites

- [ ] This issue is neither a bug report nor a feature request.
- [x] I've experience in webdevelopment
- [ ] I'm new to WordPress

## Description
Addon Ninja Forms should be updated, but the repo is not, so I am writing this here.  I have got 2 issues with latest version.

1. not able to select the agent email field in admin area

Original code:
```
if( '_hidden' == $field->get_type() )
$form_fields[ $form_field_id ] = $field['data']['label'];
```
this didn't work, I had to change it to:
```
if( 'hidden' == $field->get_setting('type') )
$form_fields[ $form_field_id ] = $field->get_setting('label');
```

2. fatal error on frontend (or warning, I am not sure now)
$ninja_forms_loading was NULL
Original code:

```
global $ninja_forms_loading; 
if( $_form_id && $_field_id && $_form_id == $form_id )
$ninja_forms_loading->update_field_value( $_field_id, antispambot( get_the_author_meta( 'email' ) ) );
```
Working code (not sure if it is the right fix)

```
$ninja_forms_loading = Ninja_Forms()->form($form_id);
if( $_form_id && $_field_id && $_form_id == $form_id ) {
	$field = $ninja_forms_loading->get_field($_field_id);
	$field->update_setting('default', antispambot(get_the_author_meta('email')));
}
```

Used position: After the end 
 
Thanks

**Comment by Jimmi08** [comment]
I don't know if this is ninja forms related or wpcasa:  UpTown theme is used.

![image](https://github.com/user-attachments/assets/3ca37c61-4979-4a3a-adde-9ca8663321c6)

**Comment by codestylist** [comment]
Thank you @Jimmi08 for your message. We have not noticed this issue yet and will investigate it further.

**Comment by Jimmi08** [comment]
@codestylist Hi Sandro,
I did fresh installation to be sure: 
**- PHP 8.1**
- WP 6.6.1 (just downloaded)
- installed wpcasa, imported demo content from wpcasa.com,  new agents created - from WP admin
- installed ninja forms, wpcasa ninja form - from WP admin
- Listing form saved and published
- UpTown theme installed and activated

Go to settings - no email field
![image](https://github.com/user-attachments/assets/fd17c33e-7915-4c0a-ae5a-ab1950d086e4)

Frontend:
![image](https://github.com/user-attachments/assets/1e6f29da-6294-4c9c-8a4a-0daad7da2889)

**Comment by Jimmi08** [comment]
> I don't know if this is ninja forms related or wpcasa: UpTown theme is used.
> 
> ![image](https://private-user-images.githubusercontent.com/5429548/351281409-3ca37c61-4979-4a3a-adde-9ca8663321c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjI3MzYsIm5iZiI6MTcyMTgyMjQzNiwicGF0aCI6Ii81NDI5NTQ4LzM1MTI4MTQwOS0zY2EzN2M2MS00OTc5LTRhM2EtYWRkZS05Y2E4NjYzMzIxYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMTIwMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzJiZjJiMDE1N2IxYThmNjRlZWI4YzBhMTcyM2FiZmYzMDhmNTg3ZjUwZDAyMGFkMDUxNGYxNTI3NDVhM2JmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t8UGP9FQvYT-Z47HjTY5KBhyvGwm1xmT-CGT-_Gkq1A)

This is ninja form issue, it is reported on official repository many times, it can be fixed in theme with filter. I posted solution there.  Just to have it complete for the future:

```
function decode_ninja_forms_display_form_settings($settings, $form_id)
{
	$settings['fieldsMarkedRequired'] = html_entity_decode($settings['fieldsMarkedRequired']);

	return $settings;
}
add_filter('ninja_forms_display_form_settings', 'decode_ninja_forms_display_form_settings', 10, 2);
```
