### ISSUE TITLE
Fix meta_box_spaces()

### ISSUE THREAD

**Issue by simonrimkus** [wpsight/wpcasa#15]
See https://cloudup.com/c8god0V31Ad

object_types parameter has to be array. Priority of space description needs to be 0 to be displayed before other fields.

**Comment by jancbeck** [comment]
What exactly is the purpose of the spaces?

**Comment by simonrimkus** [comment]
It's a relict of older versions in order to add custom meta boxes more easily. In the end it's a wrapper for the meta box API.

**Comment by jancbeck** [comment]
Should we deprecate spaces and endorse the `wpsight_meta_boxes` filter instead?
