### ISSUE TITLE
Bug in Settings - Wrong Measurement Unit?

### ISSUE THREAD

**Issue by JoeHana** [wpsight/wpcasa#17]
It seems like 1 of those 4 default measurement units displays wrong - it displays a 1 instead of a proper measurement unit. It's probably supposed to display sq yd.

![wpcasa settings wpcasa wordpress](https://cloud.githubusercontent.com/assets/122551/13201115/b78b2920-d863-11e5-9f6c-cfb356f4c850.png)

**Comment by simonrimkus** [comment]
Thanks Joe! There is a typo in the measurements array. Here's a temporary fix if necessary:

<pre>/**
 * Fix measurement units
 */
add_filter( 'wpsight_measurements', 'wpsight_measurements_fix' );

function wpsight_measurements_fix() {
	
	$measurements = array(
		''		=> '',
		'm2'	=> 'm&sup2;',
		'sqft'	=> 'sq ft',
		'sqyd'	=> 'sq yd',
		'acres'	=> 'acre(s)'
	);
	
	return $measurements;
	
}</pre>
