### ISSUE TITLE
Bug with wpsight_listings shortcode attributes

### ISSUE THREAD

**Issue by JoeHana** [wpsight/wpcasa#34]
It seems like the shortcode ignore URL Parameters to order listings.

Eg. by using [wpsight_listings orderby="price" order="ASC"] the original order works fine, but if the user re-orders them live from the dropdown, the results will stay the same.

The shortcode probably needs to first check if URL Parameters are available and only apply the shortcode attributes if there are no URL Parameters.

**Comment by simonrimkus** [comment]
Closing as a duplicate of #25
