### ISSUE TITLE
Warning: join(): Invalid arguments passed in /home2/taoliyi/public_html/linkystone.com/wp-content/plugins/wpcasa/functions/wpsight-template.php on line 262 class="" itemscope itemtype="http://schema.org/Product">

### ISSUE THREAD

**Issue by JoeHana** [wpsight/wpcasa#41]
This issue occurs when having a page with either the [wpsight_listings] shortcode or a query page template active while also having a Listing Query widget in the sidebar.

**Comment by fabianmarz** [comment]
I can't reproduce this warning. What shortcode are you calling in your widget? Or is this a theme related issue?

**Comment by JoeHana** [comment]
Finally there has been another case where this issue happened. After digging through I found that this issue occurs in conjunction with the "Recent Posts" widget. Need to check what exactly is causing this.

**Comment by JoeHana** [comment]
Obviously it doesn't even matter if the sidebar is visible or not. As soon as there is a recent posts widget it will cause this fatal error.
