### ISSUE TITLE
Rent period untranslated

### ISSUE THREAD

**Issue by AndyManzi** [wpsight/wpcasa#50]
Hi, there is a problem with the translation of rental period.
If you choose another language, you will see "per month, per week ..etc..." yet. ... .rental period is translated correctly in .po and .mo files
Thanks
Andy

**Comment by JoeHana** [comment]
You can change the wording of the rental periods within the WPCasa Settings. If you run your website multilingual (Polylang) you can translate those through the string translation from Polylang.

**Comment by AndyManzi** [comment]
Hello Joe,
thank you for reply. I found it ! ;-).
But .... "per Month", "per Week", "per Year", "per Day" are terms that I have found in .po file. Translation's file are required from include/class-wpsight-general.php (https://github.com/wpsight/wpcasa/blob/master/wpcasa/includes/class-wpsight-general.php#L361); On which part of plug-ins can I find this terms translated?

**Comment by JoeHana** [comment]
This is more of the default language. If you install WPCasa and haven't saved any settings yet and have your WordPress Language set to eg. german than the german translation should display within those fields.

**Comment by AndyManzi** [comment]
Hello Joe,
      thank you very much for your explanation.
      
      
      Il 01/02/2017 16:03, Joe Hana ha scritto:
    
    
      This is more of the default language. If you install WPCasa and
        haven't saved any settings yet and have your WordPress Language
        set to eg. german than the german translation should display
        within those fields.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wpsight/wpcasa","title":"wpsight/wpcasa","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wpsight/wpcasa"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JoeHana in #50: This is more of the default language. If you install WPCasa and haven't saved any settings yet and have your WordPress Language set to eg. german than the german translation should display within those fields. "}],"action":{"name":"View Issue","url":"https://github.com/wpsight/wpcasa/issues/50#issuecomment-276680231"}}}
