### ISSUE TITLE
[Q&A] Project development satus

### ISSUE THREAD

**Issue by fabianmarz** [wpsight/wpcasa#53]
@JoeHana, can you please give a status update about the current plugin development status? Is it still active? I'm asking because the open PRs didn't get attention yet. Thank you :)

**Comment by JoeHana** [comment]
Hi Fabian,

yes of course, this project is still active. And indeed we noticed the PRs and will merge them with the next release.

And since I now have the chance: Thank you for all your efforts so far. Much appreceated.

**Comment by fabianmarz** [comment]
Thanks for the update, Joe! You're welcome! I'm working with the plugin at a current project and it was the best real estate plugin we found so far.

Thank you for your work 💯
