### ISSUE TITLE
Incorrect German translation

### ISSUE THREAD

**Issue by colourgarden** [wpsight/wpcasa#63]
We found an issue where the German word 'Aktive' is being incorrectly translated. It was assumed this was a mistake in the `.po` file but we've found this is a wider issue with the way the translation is handled.

![aktivee](https://cloud.githubusercontent.com/assets/793191/26819848/01520672-4aa1-11e7-96ba-1a9fd93396fa.png)

The following line from [`class-wpsight-admin.php`](https://github.com/wpsight/wpcasa/blob/master/wpcasa/includes/admin/class-wpsight-admin.php#L407) is the one causing the issue.

`$views['publish'] = str_replace( __( 'Published' ), __( 'Active', 'wpcasa' ), $views['publish'] );`

The problem is caused because the German singular for 'Published' is 'Veröffentlicht' whereas the plural is 'Veröffentlichte'. This means that when the above line attempts the string replace on 'Veröffentlicht', the 'e' is left on the end, creating 'Aktivee'.

We played around with a quick fix and came up with a regex expression to translate any word after a closing HTML > but this isn't really any more stable than the existing solution.

`$views['publish'] = preg_replace( '@>[\p{L}]+@u', '>' . __( 'Active', 'wpcasa' ), $views['publish'] );`

**Comment by JoeHana** [comment]
Thanks for the heads up. There is indeed an issue. But it is obviously quite easy to solve. Just add the textdomain to the "Published" Textstring. This have solved this issue on my test installation. Here again the whole line:

```
$views['publish'] = str_replace( __( 'Published', 'wpcasa' ), __( 'Active', 'wpcasa' ), $views['publish'] );
```

Thanks again for your report. We will include a proper fix in the next release.
