### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by detantes** [wpsight/wpcasa#64]
Link at 
Listings - Features: 'Choose from the most used features' 
is linked to Listing types: 'Choose from the most used features' and not to Features.

**Comment by JoeHana** [comment]
What version of WPCasa are you using? Does it work if you disable all other plugins but not the WPCasa plugin?

**Comment by detantes** [comment]
Last update and yea, same problem without the non wpcasa plugins

**Comment by JoeHana** [comment]
Since we haven't got any further reports for this issue so far which would prove that this is a general bug which affects every user, I'm now closing this issue for now.

If you believe you're still having this issue, feel free to re-open this issue again.

Thanks for understanding.
