### ISSUE TITLE
Roadmap of the project

### ISSUE THREAD

**Issue by florianrusch** [wpsight/wpcasa#72]
Hey, everybody,

my client and I would like to know if this project is still in progress. The last commit was 3.5 months ago.

We are currently using the old theme-based variant and are planning to relaunch the website at the beginning of next year. In this context, we are considering whether it is worthwhile for us to continue using wpCasa.

If you have a roadmap, we would be very interested in it. We like wpCasa very much, but currently it doesn't really fit our needs.

Best regards,
Florian

**Comment by JoeHana** [comment]
Hi Florian,

yes this project is still active. We're planning to release an update soon. If you follow our blog you can see of course more activity since we're regulary release updates for various of our themes and addons.

We do not have a public roadmap available but for the next year we will release new addons and themes.

Maybe you want to share your needs?

**Comment by florianrusch** [comment]
Hi @JoeHana,

sorry, that I did not answer you. I was very busy at that time and forgot it.
We are currently working on the relaunch of our page.

Currently, we have just this two needs:
- a UI part for the energy pass which is in Germany required
- to replace the price of a property with the text "Price on request"

Further, would it be great to have a better documentation of the functions and classes of the wpCasa plugin (analogous to the WordPress Code Reference). We are creating a completely new webpage with a custom styling. So I have to override almost every single template file. :-/

Do you have a date for us, when the updates and new releases will be available? Not that I invest much time in the relaunch and you publish a completely revised wpCasa next week. :D Wouldn't be so great.

**Comment by JoeHana** [comment]
Hey @florianrusch 

thanks for your message.

Basically both of your needs is already possible:
* Energy Pass gets provided by our partner Immonex. They have a pretty decent plugin available managing the energy pass: See [here](https://wpcasa.com/downloads/immonex-energy-scale-pro/)
* This is already possible by leaving the price field blank. The text "Price on request" will then automatically display.

You're right that we need to improve the documentation for developers, but to be honest, it hasn't been that often request until now. Most of the developers do quite fine understanding the approach we use in WPCasa. So for example it might not be necessary to override all templates (altough this is a basic and common feature which definitely can be used a lot - especially when it comes to custom design), but there are also a lot of functions which you can simply override to add your custom functionality. Last but not least, the majority of functions can also be filtered. However, we have this on our radar and hopefully will be able to soon improve the developer documentation.

We're currently preparing the last beta version for WPCasa 1.1.0 and hopefully be able to release the stable version soon. I can't tell any exact date yet but it should be within the next days/weeks. But there is not much need to worry, this version won't be completely reviced and the update should go pretty smooth. However, in case you're interested I can send you the beta as soon as it becomes available, so you can have a test run too.

**Comment by florianrusch** [comment]
Hi @JoeHana 

thanks a lot for your message! 
We will give the plugin a try. ;-)

I can understand very well, that the documentation is not on the top of your todo/priority list. :-)
Currently I'm not very far with the relaunch of the website. I'm will check if I got something wrong.

It would be very awesome to be a beta tester. ;-) Just write me if it's available. We are trying to finish the relaunch in the next 2-3 weeks so I will definitely have time to include it into our side.
