### ISSUE TITLE
Fallo Buscador en Wpcasa

### ISSUE THREAD

**Issue by joseCor** [wpsight/wpcasa#73]
Hola, he instalado el pluging wpcasa en un wordpress limpio con tema up towmn.No me aparece el buscador, ni me permite poner carrusel de imagenes

**Comment by JoeHana** [comment]
Could you please re-phrase your question in english? Also - if it is an issue or question related to WPCasa or any of our themes or addons please post in the respective page:

- For WPCasa: https://wordpress.org/plugins/wpcasa/
- For upTown: https://wordpress.org/themes/uptown/

Thanks
