### ISSUE TITLE
listing carousel needs 2 listing to work

### ISSUE THREAD

**Issue by Jimmi08** [wpsight/wpcasa#76]
We use carousel filtered by category. It happened that only one listing left in that category. 
 
![image](https://user-images.githubusercontent.com/5429548/36591224-8e60708a-1891-11e8-9420-87231f43ad98.png)

Nothing is displayed and console looks like this:

![image](https://user-images.githubusercontent.com/5429548/36591169-60a165fa-1891-11e8-8410-733870707ff3.png)

with this setting

![image](https://user-images.githubusercontent.com/5429548/36591250-ab8a2282-1891-11e8-95c7-4fbc728c37b3.png)

It's impossible to check still widget settings.  And main problem is that with this error ninja form above it is not displayed either.  After adding new listing to this category, everything works, so it's has to be number of listings (or our missing setting)

Thank you

**Comment by JoeHana** [comment]
Thanks for your report. There seems indeed to be an issue with that setup. I've put this in our private repo where we manage the WPCasa Sylt Theme and it will be fixed with the next update.
