### ISSUE TITLE
fatal error in server log

### ISSUE THREAD

**Issue by Jimmi08** [wpsight/wpcasa#83]
Hi, clean installation with Bahia theme.  I can't install contact form plugin so I checked error log and noticed this:

`[fcgid:warn] [pid 12813] [xxx] mod_fcgid: stderr: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in xxx/wp-content/plugins/wpcasa/includes/class-wpsight-post-types.php on line 490, referer: xxx/wp-cron.php?doing_wp_cron=xxx`

Is this server problem or what? Thanks

**Comment by florianrusch** [comment]
It is a problem with your php settings. The amount of memory which could be used by php is not high enough. Take a look for example here: http://www.wpbeginner.com/wp-tutorials/fix-wordpress-memory-exhausted-error-increase-php-memory/

**Comment by Jimmi08** [comment]
I don't think so. Site is working, everything is working. It's just something running itself (by cron) . That example from wpbeginner is about core (wp_includes etc).  128MB should be enough for clean WP installation with basic plugins...   It's not shared hosting.  I wouldn't know about this error if I didn't check server logs.  
I posted it here to find answer what that part of code does to be able to check it. On that line is just add_filter and I wasn't able to find related function.

**Comment by florianrusch** [comment]
Mhhh, okay. Sorry, then I've miss understand your problem.

You can find the function `wpsight_delete_listing_previews` in the `wpcasa/functions/wpsight-listings.php:590`. But I don't really know where or what's the problem.

You wrote you had a clean installation. Can you give us more information about how your steps were? And does the error appears only with this plugin or also if you try to install any other plugin?
