### ISSUE TITLE
QR-Code API is deprecated

### ISSUE THREAD

**Issue by florianrusch** [wpsight/wpcasa#88]
The chart api from google which is used to generate the qr code in the print view is deprecated.

https://developers.google.com/chart/infographics/docs/qr_codes

PS: And the used api url is still connecting via http, not https.

**Comment by JoeHana** [comment]
Thanks for the heads up. As far as I can see the QR Codes still get generated though. But yes, we definitely should rework that part for the long run as well. I'm thinking about to include a QR Code Lib directly instead of using an external API.

**Comment by florianrusch** [comment]
> I'm thinking about to include a QR Code Lib directly instead of using an external API.
Sounds good :+1:

**Comment by codestylist** [comment]
@florianrusch We have fixed this in version 1.2.13.
