### ISSUE TITLE
lost of google api key

### ISSUE THREAD

**Issue by cantoute** [wpsight/wpcasa#90]
Hi,

not exactly sure when this happened, but I use to have the api key in the admin page.

perhaps after a wp updates this happened.

In the admin page ( /wp-admin/admin.php?page=wpsight-settings ) where the api key is entered, i still have a text input, but no label and no content in the text input and reputing the api key there doesn't seem to have any effect.

Thanks for your help

**Comment by JoeHana** [comment]
Maybe try to reset your Options and see if that would have any effect. Other than that I'm not sure what the issue might be other than a customization which caused this effect. However, also try to disable your plugins (except WPCasa) and see if that helps narrow down the source for this issue.
