### ISSUE TITLE
WPCasa London – A couple of bugs (fixed)

### ISSUE THREAD

**Issue by mme000** [wpsight/wpcasa#91]
I found a couple of bugs in WPCasa London theme and I fixed them.

**functions.php:120**

`'family' => 'Lato:700,400|Raleway:400,300',`

the | (pipe) character should be encoded with %7C

`'family' => 'Lato:700,400%7CRaleway:400,300',`

**includes/theme-setup.php:314**

`$pagination .= '</nav>' . "\n";`

should be substituted with

`$pagination .= '</ul></nav>' . "\n";`

**includes/theme-setup.php:318**

`$pagination = str_replace( '<li><span class=\'page-numbers current\'>', '<li class="active"><a href="#"><span class=\'page-numbers current\'>', $pagination );`

should be substituted with

`$pagination = str_replace( '<li><span aria-current=\'page\' class=\'page-numbers current\'>', '<li class="active"><a href="#"><span aria-current=\'page\' class=\'page-numbers current\'>', $pagination );`

**Comment by JoeHana** [comment]
Thank you very much. We will look into that and update accordingly.
