### ISSUE TITLE
WP 5.1: PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached

### ISSUE THREAD

**Issue by sebastienserre** [wpsight/wpcasa#93]
Hello,
I've updated to WP5.1 this morning and got this errors:
`[22-Feb-2019 10:43:14 UTC] PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /app/wp-includes/class-wp-hook.php:271
Stack trace:
#0 /app/wp-includes/class-wp-hook.php(271): array_keys(Array)
#1 /app/wp-includes/plugin.php(208): WP_Hook->apply_filters(true, Array)
#2 /app/wp-content/plugins/wpcasa/includes/class-wpsight-post-types.php(490): apply_filters('wpsight_delete_...', true)
#3 /app/wp-includes/class-wp-hook.php(286): WPSight_Post_Type_Listing->delete_listing_previews(true)
#4 /app/wp-includes/plugin.php(208): WP_Hook->apply_filters(true, Array)
#5 /app/wp-content/plugins/wpcasa/includes/class-wpsight-post-types.php(490): apply_filters('wpsight_delete_...', true)
#6 /app/wp-includes/class-wp-hook.php(286): WPSight_Post_Type_Listing->delete_listing_previews(true)
#7 /app/wp-includes/plugin.php(208): WP_Hook->apply_filters(true, Array)
#8 /app/wp-content/plugins/wpcasa/includes/class-wpsight-post-types.php(490): apply_filters('wpsight_delete_...', true)
#9 /app/wp-includes/class-wp-hook.php(286): WPSight in /app/wp-includes/class-wp-hook.php on line 271`

**Comment by JoeHana** [comment]
Where exactly did you receive this errors? Did you already disabled all plugins and switched to a standard theme?

From our side we can't verify this error at the moment. Update process to WP 5.1 went smoothly for all our test installations, but of course, if we know more we might be able to replicate this issue.

**Comment by sebastienserre** [comment]
I've this error on the debug.log when I activate WPCASA as a plugin in fresh install of WP5.1 with TwentyNineteen as theme and no other plugin activated.

**Comment by JoeHana** [comment]
I've just did a fresh install of WP 5.1 and installed WPCasa there with no other plugins active and TwentyNineteen as theme, but haven't got any errors in the debug.log. I'm unfortunately really not sure where this could come from. What version of PHP do you run on your webspace?

**Comment by sebastienserre** [comment]
![PHPinfo](https://i.imgur.com/4h45LUJ.png)
 I do not understand really what's happen.....

**Comment by sebastienserre** [comment]
I rebuild my lando/docker and errors dissapeared ... but still the errors #78
