### ISSUE TITLE
Improve PhP7.2 compliance

### ISSUE THREAD

**Issue by sebastienserre** [wpsight/wpcasa#94]
Hello
There's too much Warning in the WPCasa code...
`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /wp-content/plugins/wpcasa/includes/class-wpsight-helpers.php on line 607`

Is WPCasa Maintened?

**Comment by florianrusch** [comment]
Is far as I know yes. @JoeHana should know more about it.

**Comment by JoeHana** [comment]
Yes sure WPCasa still gets maintained. I'm currently preparing the next release where all the PHP Compatibility Issues will be fixed. Sorry for the delay.
